# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread,pyqtSignal
import time

num = 0
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 516)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.xtext = QtWidgets.QTextEdit(self.centralwidget)
        self.xtext.setGeometry(QtCore.QRect(330, 150, 61, 31))
        self.xtext.setObjectName("xtext")
        self.ytext = QtWidgets.QTextEdit(self.centralwidget)
        self.ytext.setGeometry(QtCore.QRect(400, 150, 61, 31))
        self.ytext.setObjectName("ytext")
        self.confirmbtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmbtn.setGeometry(QtCore.QRect(500, 110, 111, 121))
        self.confirmbtn.setStyleSheet("background-color: rgb(255, 177, 226);\n"
"color:black;\n"
"border-style:outset;\n"
"border-color:black;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"font:bold 20px;\n"
"")
        self.confirmbtn.setObjectName("confirmbtn")
        self.xlabel = QtWidgets.QLabel(self.centralwidget)
        self.xlabel.setGeometry(QtCore.QRect(350, 190, 60, 16))
        self.xlabel.setObjectName("xlabel")
        self.ylabel = QtWidgets.QLabel(self.centralwidget)
        self.ylabel.setGeometry(QtCore.QRect(419, 190, 61, 21))
        self.ylabel.setObjectName("ylabel")
        self.backbtn = QtWidgets.QPushButton(self.centralwidget)
        self.backbtn.setGeometry(QtCore.QRect(310, 420, 141, 51))
        self.backbtn.setStyleSheet("background-color: rgb(34, 106, 200);\n"
"color:white;\n"
"border-color:black;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.backbtn.setObjectName("backbtn")
        self.nextbtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextbtn.setGeometry(QtCore.QRect(460, 420, 141, 51))
        self.nextbtn.setStyleSheet("background-color: rgb(34, 106, 200);\n"
"color:white;\n"
"border-color:black;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.nextbtn.setAutoDefault(False)
        self.nextbtn.setDefault(False)
        self.nextbtn.setFlat(False)
        self.nextbtn.setObjectName("nextbtn")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 281, 461))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("1.jpeg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.Startbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Startbtn.setGeometry(QtCore.QRect(320, 20, 281, 32))
        self.Startbtn.setObjectName("Startbtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 110, 151, 121))
        self.label.setStyleSheet("border-style:outset;\n"
"border-width:1px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 120, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.xtext.raise_()
        self.ytext.raise_()
        self.confirmbtn.raise_()
        self.xlabel.raise_()
        self.ylabel.raise_()
        self.backbtn.raise_()
        self.nextbtn.raise_()
        self.photo.raise_()
        self.Startbtn.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sponsored by Puco"))
        self.xtext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">none</p></body></html>"))
        self.ytext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">none</p></body></html>"))
        self.confirmbtn.setText(_translate("MainWindow", "confirm"))
        self.xlabel.setText(_translate("MainWindow", "X"))
        self.ylabel.setText(_translate("MainWindow", "Y"))
        self.backbtn.setText(_translate("MainWindow", "back"))
        self.nextbtn.setText(_translate("MainWindow", "next"))
        self.Startbtn.setText(_translate("MainWindow", "Press to start record x,y cordinates"))
        self.label_2.setText(_translate("MainWindow", "Cordinates:"))
        self.backbtn.clicked.connect(self.backward)
        self.nextbtn.clicked.connect(self.forward)
        self.Startbtn.clicked.connect(self.startThread)

    def backward(self):
        global num
        if num >=1:
            num-=1
            self.photo.setPixmap(QtGui.QPixmap('%s.jpeg'%num))
        else:
            num = 1
            self.photo.setPixmap(QtGui.QPixmap('%s.jpeg' % num))
    def forward(self):
        global num
        if num <=4:
            num+=1
            self.photo.setPixmap(QtGui.QPixmap('%s.jpeg'%num))
        else:
            self.photo.setPixmap(QtGui.QPixmap('%s.jpeg' % (num-1)))





    def startThread(self):
        self.worker = Worker()
        self.worker.start()
        print('start')
        self.worker.xcordinate.connect(self.setx)
        self.worker.ycordinate.connect(self.sety)

    def setx(self,val):
        self.xtext.setText(str(val))
    def sety(self,val):
        self.ytext.setText(str(val))

class Worker(QThread):
    xcordinate = pyqtSignal(int)
    ycordinate = pyqtSignal(int)
    def run(self):
        cmd = r'adb shell getevent'
        w = 0
        h = 0
        try:
            p1 = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
            for line in p1.stdout:
                line = line.decode(encoding="utf-8", errors="ignore")
                line = line.strip()

                if ' 0035 ' in line:
                    e = line.split(" ")
                    w = e[3]
                    w = int(w, 16)

                if ' 0036 ' in line:
                    e = line.split(" ")
                    h = e[3]
                    h = int(h, 16)
                    if h > 0:
                        x = w
                        y = h
                        self.xcordinate.emit(x)
                        self.ycordinate.emit(y)

            p1.wait()
        except Exception as e:
            print(e)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
